name: Check GET Request

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  check_get_request:
    name: Check GET Request
    runs-on: ubuntu-latest

    steps:

      - name: Send GET request and verify response
        run: |
          response=$(curl -o /dev/null -s -w "%200" https://mc-backend-ykec.onrender.com/menu/StartersVegMenu)
          echo response
          if [ "$response" = "200" ]; then
            echo "GET request successful - HTTP 200 OK"
            exit 0
          else
            echo "GET request failed - HTTP $response"
            exit 1
          fi
